# Generated by Django 3.2.2 on 2021-05-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20210505_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='votes',
            new_name='comment_date',
        ),
    ]
